src/SecelPartner/Controllers/GerantController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using SecelPartner.Core.Entities;
using SecelPartner.Core.Interfaces;
using SecelPartner.UI.Data;
using SecelPartner.UI.Interfaces;
using SecelPartner.UI.Migrations;
using SecelPartner.UI.Models;

namespace SecelPartner.UI.Controllers
{
    [Authorize(Roles = "Super Administrateur")]
    public class GerantController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly IGerantRepository _gerantRepository;
        private readonly IUnitOfWork _unitOfWork;

        public GerantController(
            SecelPartnerUIContext context,
            IUnitOfWork unitOfWork,
            IUserRepository userRepository,
            IGerantRepository gerantRepository
        )
        {
            _userRepository = userRepository;
            _gerantRepository = gerantRepository;
            _unitOfWork = unitOfWork;
        }

        // GET: Gerant
        public async Task<IActionResult> Index()
        {
            var secelPartnerUIContext = await _gerantRepository.GetAll();
            return View(secelPartnerUIContext);
        }

        // GET: Gerant/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var gerant = await _gerantRepository.GetById(id);
                if (gerant != null)
                {
                    return View(gerant);
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            TempData["errorMessage"] = $"Niveau gerant with Id = {id} not found";
            return RedirectToAction(nameof(Index));
        }

        // GET: Gerant/Create
        public IActionResult Create()
        {
            try
            {
                if (
                    _unitOfWork.Contrats.ListItems().Count == 0
                    || _gerantRepository.ListItems().Count == 0
                )
                {
                    TempData["warningMessage"] =
                        "Vous devez enregistrer au moins un contrat de partenariat avant d'y attribuer un Administrateur";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.ContratPartenariatList = _unitOfWork.Contrats.ListItems();
                    ViewBag.UserList = _gerantRepository.ListItems();
                    return View();
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex;
                return RedirectToAction("Index");
            }
        }

        // POST: Gerant/Create

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Gerant gerant)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _gerantRepository.Add(gerant);
                    TempData["successMessage"] = "Chef Partenariat create successfully !!";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.ContratPartenariatList = _unitOfWork.Contrats.ListItems();
                    ViewBag.UserList = _gerantRepository.ListItems();
                    TempData["errorMessage"] = "Model state is Invalid ";
                    return View();
                }
            }
            catch (Exception? ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        // GET: Gerant/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            ViewBag.ContratPartenariatList = _unitOfWork.Contrats.ListItems();
            ViewBag.UserList = _userRepository.ListItems();
            var gerant = await _gerantRepository.GetById(id);
            if (gerant != null)
            {
                return View(gerant);
            }
            else
            {
                TempData["errorMessage"] = $"gerant details not found with Id : {id}";
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Gerant/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Gerant gerant)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    await _gerantRepository.Update(gerant);
                    _unitOfWork.Complete();
                    TempData["successMessage"] = "gerant update successfully !!";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.ContratPartenariatList = _unitOfWork.Contrats.ListItems();
                    ViewBag.UserList = _gerantRepository.ListItems();
                    TempData["errorMessage"] = "Une erreur cest produite verifier vos champ ";
                    return View(gerant);
                }
            }
            catch (Exception? ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Gerant/Delete/5
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var gerant = await _gerantRepository.GetById(id);
                if (gerant != null)
                {
                    return View(gerant);
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            TempData["errorMessage"] = $"gerant with Id = {id} not found";
            return RedirectToAction(nameof(Index));
        }

        // POST: Gerant/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                await _gerantRepository.Delete(id);
                _unitOfWork.Complete();
                TempData["successMessage"] = "gerant Delete successfully !!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception? ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

src/SecelPartner/Controllers/UserController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SecelPartner.Core.Entities;
using SecelPartner.Core.Interfaces;
using SecelPartner.infrastructure.Services;
using SecelPartner.UI.Areas.Identity.Data;
using SecelPartner.UI.Interfaces;

namespace SecelPartner.UI.Controllers
{
    public class UserController : Controller
    {
        private readonly IUserRoleRepository _userRoleRepository;
        private readonly IUserRepository _userRepository;
        private readonly RoleManager<IdentityRole> _roleManager;
        private readonly UserManager<SecelPartnerUIUser> _userManager;
        private readonly IUnitOfWork _unitOfWork;
        private readonly FichierService _fichierService;

        public UserController(
            IUserRoleRepository userRoleRepository,
            FichierService fichierService,
            IUserRepository userRepository,
            IUnitOfWork unitOfWork,
            RoleManager<IdentityRole> roleManager,
            UserManager<SecelPartnerUIUser> userManager
        )
        {
            _roleManager = roleManager;
            _userManager = userManager;
            _unitOfWork = unitOfWork;
            _userRoleRepository = userRoleRepository;
            _userRepository = userRepository;
            _fichierService = fichierService;
        }

        // GET: UserController
        [Authorize(Roles = "Super Administrateur")]
        public async Task<IActionResult> Index()
        {
            var user = await _userRepository.GetAll();
            ViewBag.UserRoles = await _userRoleRepository.GetAll();
            ViewBag.Roles = _roleManager.Roles.ToList();
            return View(user);
        }

        // GET: UserController/Details/5
        [Authorize(Roles = "Super Administrateur")]
        public async Task<IActionResult> Details(string id)
        {
            try
            {
                var user = await _userRepository.GetById(id);
                if (user != null)
                {
                    return View(user);
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            TempData["errorMessage"] = $"User with Id = {id} not found";
            return RedirectToAction(nameof(Index));
        }

        // GET: UserController/Edit/5
        [Authorize(Roles = "Super Administrateur")]
        public async Task<IActionResult> Edit(string id)
        {
            var user = await _userRepository.GetById(id);
            if (user != null)
            {
                return View(user);
            }
            else
            {
                TempData["errorMessage"] = $"user details not found with Id : {id}";
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: UserController/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Super Administrateur")]
        public async Task<IActionResult> Edit(SecelPartnerUIUser user)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (user.Profil != null)
                    {
                        user.ProfilName = user.Profil.FileName;
                        user.ProfilPath = await _fichierService.UploadAsync(user.Profil);
                    }
                    await _userRepository.Update(user);
                    TempData["successMessage"] = "Contact update successfully !!";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    ViewBag.RoleList = _roleManager.Roles.ToList();
                    TempData["errorMessage"] = "Model state is Invalid ";
                    return View(user);
                }
            }
            catch (Exception? ex)
            {
                ViewBag.PartenaireList = _unitOfWork.Partenaires.ListItems();
                TempData["errorMessage"] = ex.Message;
                return View(user);
            }
        }

        [Authorize(Roles = "Super Administrateur")]
        // GET: UserController/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            try
            {
                var user = await _userRepository.GetById(id);
                if (user != null)
                {
                    return View(user);
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            TempData["errorMessage"] = $"Contact with Id = {id} not found";
            return RedirectToAction(nameof(Index));
        }

        // POST: UserController/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Super Administrateur")]
        public async Task<IActionResult> Deleteconfirmed(string id)
        {
            try
            {
                var user = await _userRepository.GetById(id);
                if (null != user.ProfilPath)
                {
                    _fichierService.DeleteUploadFile(user.ProfilPath);
                }
                await _userRepository.Delete(id);
                TempData["successMessage"] = "user Delete successfully !!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception? ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }

        public async Task<IActionResult> MailUser(string id)
        {
            try
            {
                if (_userRepository.ListItems().Count == 0)
                {
                    TempData["warningMessage"] = "Vous devez enregistrer au moins un utilisateur";
                    return RedirectToAction("Index");
                }
                else
                {
                    ViewBag.UserList = _userRepository.ListItems();
                    if (id == null)
                    {
                        return View();
                    }
                    var user = await _userRepository.GetById(id);
                    if (user != null)
                    {
                        ViewBag.user = user;
                        return View();
                    }
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            TempData["errorMessage"] = $"user with Id = {id} not found";
            return RedirectToAction(nameof(Index));
        }

        [HttpPost]
        public async Task<IActionResult> MailUser(SendEmail sendEmail)
        {
            try
            {
                ViewBag.userList = _userRepository.ListItems();
                var user = await _userManager.GetUserAsync(User);
                sendEmail.FromEmail = user.Email;
                sendEmail.Name = user.FirstName + " " + user.LastName;
                if (user.PhoneNumber == null)
                {
                    TempData["warningMessage"] =
                        "Votre numero de telephone est requit ... MyAccount>Profil";
                    return RedirectToAction("Index");
                }
                sendEmail.Tel = Int32.Parse(user.PhoneNumber);
                _unitOfWork.Emails.EmailSend(sendEmail);
                await _unitOfWork.Emails.Add(sendEmail);
                _unitOfWork.Complete();
                TempData["successMessage"] = $"Mail send successfully to {sendEmail.ToEmail}";
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }
    }
}

src/SecelPartner/Views/Shared/_AdminNav.cshtml
<!-- Main Sidebar Container -->
<aside class="main-sidebar dark-mode sidebar-dark-primary elevation-4">
        <a href="#" class="brand-link">
            <img src="~/img/p.png" alt="Sp Logo" class="brand-image img-circle elevation-3" style="opacity: .8">
            <span class="brand-text font-weight-light">Secel-Partner</span>
        </a>
    <!-- Sidebar -->
    <div class="sidebar">
        <!-- SidebarSearch Form -->
        <div class="form-inline">
            <div class="input-group" data-widget="sidebar-search">
                <input class="form-control form-control-sidebar" type="search" placeholder="Search" aria-label="Search">
                <div class="input-group-append">
                    <button class="btn btn-sidebar">
                        <i class="fas fa-search fa-fw"></i>
                    </button>
                </div>
            </div>
        </div>
        <!-- Sidebar Menu -->
        <nav class="mt-2">
            <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                <!-- Dashboard -->
                <li class="nav-item">
                    <a asp-controller="Dashbroad" asp-action="DashbroadAdmin" class="nav-link " >
                        <i class="nav-icon fas fa-tachometer-alt"></i>
                        <p>
                            Dashboard
                        </p>
                    </a>
                </li>
                <!-- Partenariat -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-regular fa-handshal fa-handshake nav-icon"></i>
                        <p>
                            partenariat
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="Partenariat" class="nav-link" >
                                <i class="fa-solid fa-list nav-icon"></i>
                                <p>list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Create" asp-controller="Partenariat" class="nav-link" >
                                <i class="fa-solid fa-plus nav-icon"></i>
                                <p>add</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- ContratPartenariat -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-file-contract nav-icon" onclick="WebGLActiveInfo"></i>
                        <p>
                            Contrat partenariat
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-action="Index" asp-controller="ContratPartenariat" class="nav-link" onclick="WebGLActiveInfo">
                                <i class="fa-solid fa-list nav-icon"></i>
                                <p>list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-action="Create" asp-controller="ContratPartenariat" class="nav-link" onclick="WebGLActiveInfo">
                                <i class="fa-solid fa-plus nav-icon"></i>
                                <p>add</p>
                            </a>
                        </li>
        
                    </ul>
                </li>
                <!-- Partenaires -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class=" fa-solid fa-handshake" onclick="active"></i>
                        <p>
                            Partenaires
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview mr-2">
                        <li class="nav-item">
                            <a asp-controller="Partenaire" asp-action="Index" class="nav-link" onclick="active">
                                <i class="fa-solid fa-list nav-icon"></i>
                                <p>list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Partenaire" asp-action="Create" class="nav-link" onclick="active">
                                <i class="fa-solid fa-plus nav-icon"></i>
                                <p>add</p>
                            </a>
                        </li>
                      </ul>
                </li>
                <!-- Contacts -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-address-book nav-icon"></i>
                        <p>
                            Contacts
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Contact" asp-action="Index" class="nav-link">
                                <i class="fa-solid fa-list nav-icon"></i>
                                <p>list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Contact" asp-action="Create" class="nav-link">
                                <i class="fa-solid fa-plus nav-icon"></i>
                                <p>add</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- Niveau Partenariat -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid fa-arrow-turn-up nav-icon"></i>
                        <p>
                            Niveau partenariat
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="NiveauPartenariat" asp-action="Index" class="nav-link">
                                <i class="fa-solid fa-list nav-icon"></i>
                                <p>list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="NiveauPartenariat" asp-action="Create" class="nav-link">
                                <i class="fa-solid fa-plus nav-icon"></i>
                                <p>add</p>
                            </a>
                        </li>
  
                    </ul>
                </li>
                <!-- Type Partenariat -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="fa-solid nav-icon fa-text-height"></i>
                        <p>
                            Type partenariat
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="TypePartenariat" asp-action="Index" class="nav-link">
                                <i class="fa-solid fa-list nav-icon"></i>
                                <p>list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="TypePartenariat" asp-action="Create" class="nav-link">
                                <i class="fa-solid fa-plus nav-icon"></i>
                                <p>add</p>
                            </a>
                        </li>
    
                    </ul>
                </li>
                <!-- Chef Partenariat -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class=" fa-solid fa-person-military-to-person nav-icon"></i>
                        <p>
                            Chef Partenariat
                            <i class="fas fa-angle-left right"></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Gerant" asp-action="Index" class="nav-link">
                                <i class="fa-solid fa-list nav-icon"></i>
                                <p>list</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="Gerant" asp-action="Create" class="nav-link">
                                <i class="fa-solid fa-plus nav-icon"></i>
                                <p>add</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- Send Mail  -->
                <li class="nav-item">
                    <a href="#" class="nav-link">
                        <i class="nav-icon far fa-comment "></i>
                        <p>
                            Send Mail To 
                            <i class="fas fa-angle-left right "></i>
                        </p>
                    </a>
                    <ul class="nav nav-treeview">
                        <li class="nav-item">
                            <a asp-controller="Contact" asp-action="MailContact" class="nav-link">
                                <i class="fa-regular fa-message nav-icon"></i>
                                <p>Contact</p>
                            </a>
                        </li>
                        <li class="nav-item">
                            <a asp-controller="User" asp-action="MailUser" class="nav-link">
                                <i class="fa-solid fa-message nav-icon"></i>
                                <p>User</p>
                            </a>
                        </li>
                    </ul>
                </li>
                <!-- Avantages -->
                <li class="nav-item">
                    <a asp-controller="Avantage" asp-action="Index" class="nav-link " id="email">
                        <i class="nav-icon fa-solid fa-area-chart"></i>
                        <p>
                            Avantages
                        </p>
                    </a>
                </li>
                <!-- Conditions -->
                <li class="nav-item">
                    <a asp-controller="Condition" asp-action="Index" class="nav-link " id="email">
                        <i class="nav-icon fas fa-info"></i>
                        <p>
                            Conditions
                        </p>
                    </a>
                </li>
                <!-- Conditions de MAJ -->
                <li class="nav-item">
                    <a asp-controller="ConditionRenouv" asp-action="Index"  class="nav-link " id="email">
                        <i class="fa-solid fa-rotate-right nav-icon"></i>
                        <p>
                            Conditions de MAJ
                        </p>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- /.sidebar-menu -->
    </div>
    <!-- /.sidebar -->
</aside>

src/SecelPartner/Views/Shared/_LayoutRapport.cshtml
<!DOCTYPE html>

<html>
<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Secel partner | Rapport Print</title>

    <!-- Google Font: Source Sans Pro -->
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&display=fallback">
    <!-- Font Awesome -->
    <link rel="stylesheet" href="~/plugins/fontawesome-free/css/all.min.css">
    <!-- Theme style -->
    <link rel="stylesheet" href="~/css/adminlte.min.css">

</head>
<body>
    <div class="wrapper">
        <!-- Main content -->
        @RenderBody()
    </div>
</body>
</html>