src/SecelPartner/Controllers/PartenaireController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SecelPartner.Core.Entities;
using SecelPartner.Core.Interfaces;
using SecelPartner.infrastructure.Services;
using SecelPartner.UI.Areas.Identity.Data;
using SecelPartner.UI.Interfaces;
using SecelPartner.UI.Migrations;

namespace SecelPartner.UI.Controllers
{
    [Authorize]
    public class PartenaireController : Controller
    {
        #region membres prives
        private readonly IUnitOfWork _unitOfWork;
        private readonly FichierService _fichierService;
        private readonly IGerantRepository _gerantRepository;
        private readonly UserManager<SecelPartnerUIUser> _userManager;
        #endregion

        #region constructeur
        public PartenaireController(
            IUnitOfWork unitOfWork,
            FichierService fichierService,
            IGerantRepository gerantRepository,
            UserManager<SecelPartnerUIUser> userManager
        )
        {
            _unitOfWork = unitOfWork;
            _fichierService = fichierService;
            _userManager = userManager;
            _gerantRepository = gerantRepository;
        }
        #endregion
        // GET: Partenaire
        public async Task<IActionResult> Index()
        {
            var partenaires = await _unitOfWork.Partenaires.GetAll();
            return View(partenaires);
        }

        [Authorize(Roles = "Chef de partenariat")]
        public async Task<IActionResult> IndexGerant()
        {
            var Id = _userManager.GetUserId(User);
            var contrats = await _unitOfWork.Contrats.GetAll();
            var Partenaires = await _unitOfWork.Partenaires.GetAll();
            var PartenairesGerant = _gerantRepository.ListPartenaireGerant(
                Id,
                contrats,
                Partenaires
            );
            return View(PartenairesGerant.Distinct());
        }

        // GET: Partenaire/Details/5
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var partenaire = await _unitOfWork.Partenaires.GetById(id);
                if (partenaire != null)
                {
                    return View(partenaire);
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            TempData["errorMessage"] = $"partenaire with Id = {id} not found";
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Administrateur")]
        // GET: Partenaire/Create
        [Authorize(Roles = "Administrateur,Super Administrateur")]
        public IActionResult Create()
        {
            return View();
        }

        // POST: Partenaire/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Administrateur,Super Administrateur")]
        public async Task<IActionResult> Create(Partenaire partenaire)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (partenaire.Logo != null)
                    {
                        partenaire.LogoName = partenaire.Logo.FileName;
                        partenaire.LogoPath = await _fichierService.UploadAsync(partenaire.Logo);
                    }
                    await _unitOfWork.Partenaires.Add(partenaire);
                    _unitOfWork.Complete();
                    TempData["successMessage"] = "Partener create successfully !!";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["errorMessage"] = "Model state is Invalid ";
                    return View();
                }
            }
            catch (Exception? ex)
            {
                TempData["errorMessage"] = ex.Message;
                return View();
            }
        }

        // GET: Partenaire/Edit/5
        public async Task<IActionResult> Edit(int id)
        {
            var partenaire = await _unitOfWork.Partenaires.GetById(id);
            if (partenaire != null)
            {
                return View(partenaire);
            }
            else
            {
                TempData["errorMessage"] = $"Partenaire details not found with Id : {id}";
                return RedirectToAction(nameof(Index));
            }
        }

        // POST: Partenaire/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Partenaire partenaire)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    if (partenaire.Logo != null)
                    {
                        partenaire.LogoName = partenaire.Logo.FileName;
                        partenaire.LogoPath = await _fichierService.UploadAsync(partenaire.Logo);
                    }
                    await _unitOfWork.Partenaires.Update(partenaire);
                    _unitOfWork.Complete();
                    TempData["successMessage"] = "Partner update successfully !!";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    TempData["errorMessage"] = "Model state is Invalid ";
                    return View(partenaire);
                }
            }
            catch (Exception? ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction("Index");
            }
        }

        // GET: Partenaire/Delete/5
        [Authorize(Roles = "Super Administrateur")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var partenaire = await _unitOfWork.Partenaires.GetById(id);
                if (partenaire != null)
                {
                    return View(partenaire);
                }
            }
            catch (Exception ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
            TempData["errorMessage"] = $"Partner with Id = {id} not found";
            return RedirectToAction(nameof(Index));
        }

        // POST: Partenaire/Delete/5
        [Authorize(Roles = "Super Administrateur")]
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            try
            {
                var partenaire = await _unitOfWork.Partenaires.GetById(id);
                if (null != partenaire.LogoPath)
                {
                    _fichierService.DeleteUploadFile(partenaire.LogoPath);
                }
                await _unitOfWork.Partenaires.Delete(id);
                _unitOfWork.Complete();
                TempData["successMessage"] = "Partner Delete successfully !!";
                return RedirectToAction(nameof(Index));
            }
            catch (Exception? ex)
            {
                TempData["errorMessage"] = ex.Message;
                return RedirectToAction(nameof(Index));
            }
        }
    }
}

src/SecelPartner/Views/Partenaire/Create.cshtml
@model SecelPartner.Core.Entities.Partenaire

@{
    ViewData["STitle"] = "Partenaire/Create";
    ViewData["Title"] = "Create a new partner";
}

<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create" enctype="multipart/form-data">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nom" class="control-label"></label>
                <input asp-for="Nom" class="form-control" />
                <span asp-validation-for="Nom" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Adresse" class="control-label"></label>
                <input asp-for="Adresse" class="form-control" />
                <span asp-validation-for="Adresse" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumTel" class="control-label"></label>
                <input asp-for="NumTel" class="form-control" />
                <span asp-validation-for="NumTel" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Siteweb" class="control-label"></label>
                <input asp-for="Siteweb" class="form-control" />
                <span asp-validation-for="Siteweb" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SecteurAc" class="control-label"></label>
                <input asp-for="SecteurAc" class="form-control" />
                <span asp-validation-for="SecteurAc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Statut" class="control-label"></label>
                <input asp-for="Statut" class="form-control" />
                <span asp-validation-for="Statut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Logo" class="control-label"></label>
                <input type="file" asp-for="Logo" class="form-control" />
                <span asp-validation-for="Logo" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

src/SecelPartner/Views/Partenaire/Delete.cshtml
@model SecelPartner.Core.Entities.Partenaire

@{
    ViewData["Title"] = "Delete";
    ViewData["STitle"] = "Partenaire/Delete";
}

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Partenaire</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Nom)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Nom)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Adresse)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Adresse)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.NumTel)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.NumTel)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Siteweb)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Siteweb)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.SecteurAc)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.SecteurAc)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Statut)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Statut)
        </dd>
        <dt class="col-sm-2">
            @*@Html.DisplayNameFor(model => model.Logo)*@
        </dt>
        <dd class="col-sm-10">
            @*@Html.DisplayFor(model => model.Logo)*@
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" class="btn btn-success">Back to List</a>
    </form>
</div>

src/SecelPartner/Views/Partenaire/Index.cshtml
@model IEnumerable<SecelPartner.Core.Entities.Partenaire>
@{
    ViewData["Title"] = "Liste des Partnaires ";
    ViewData["STitle"] = "Partenaire / Index";
}
<!-- DataTables -->
<link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <button asp-controller="Partenaire" asp-action="Create" class="btn btn-primary mb-3">New Partner</button>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Nom)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Adresse)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NumTel)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Siteweb)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SecteurAc)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Statut)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Logo)
                                    </th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Nom)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Adresse)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NumTel)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Siteweb)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SecteurAc)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Statut)
                                        </td>
                                        <td>
                                            @if (item.LogoPath != null)
                                            {
                                                <img src="@Url.Content(item.LogoPath)" alt="@item.Nom" class="img-circle " wight="80" height="80" />
                                            }
                                            else
                                            {
                                                <img src="~/Fichiers/P.png" alt="user-avatar" class="img-circle " wight="80" height="80" />
                                            }
                                        </td>
                                        <td class="text-center">
                                            <div class="btn-group btn-group-sm">
                                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success">Details</a>
                                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">  Edit </a>
                                                @if (this.User.IsInRole("Super Administrateur"))
                                                {
                                                    <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                                }
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Nom)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Adresse)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NumTel)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Siteweb)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SecteurAc)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Statut)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Logo)          
                                    </th>
                                    <th>Actions</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!--/. container-fluid -->
</section>
<!-- /.content -->
<!-- AdminLTE App -->
<script src="~/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/js/demo.js"></script>
<!-- DataTables  & Plugins -->
<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/plugins/jszip/jszip.min.js"></script>
<script src="~/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<!-- Page specific script -->
<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
</script>

src/SecelPartner/Views/Partenaire/IndexGerant.cshtml
@model IEnumerable<SecelPartner.Core.Entities.Partenaire>
@{
    ViewData["Title"] = "Liste des Partnaires ";
    ViewData["STitle"] = "Partenaire / IndexGerant";
}
<!-- DataTables -->
<link rel="stylesheet" href="~/plugins/datatables-bs4/css/dataTables.bootstrap4.min.css">
<link rel="stylesheet" href="~/plugins/datatables-responsive/css/responsive.bootstrap4.min.css">
<link rel="stylesheet" href="~/plugins/datatables-buttons/css/buttons.bootstrap4.min.css">
<!-- Main content -->
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header">
                        <button asp-controller="Partenaire" asp-action="Create" class="btn btn-primary mb-3">New Partner</button>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example1" class="table table-bordered table-striped">
                            <thead>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Nom)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Adresse)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NumTel)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Siteweb)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SecteurAc)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Statut)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Logo)
                                    </th>
                                    <th>Actions</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Nom)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Adresse)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.NumTel)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Email)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Siteweb)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.SecteurAc)
                                        </td>
                                        <td>
                                            @Html.DisplayFor(modelItem => item.Statut)
                                        </td>
                                        <td>
                                            @if (item.LogoPath != null)
                                            {
                                                <img src="@Url.Content($"~/{item.LogoPath}")" alt="@item.Nom" class="img-circle img-fluid" wight="128" height="128" />
                                            }
                                            else
                                            {
                                                <img src="~/Fichiers/P.png" alt="user-avatar" class="img-circle img-fluid" wight="100" height="100" />
                                            }
                                        </td>
                                        <td class="text-center">
                                            <div class="btn-group btn-group-sm">
                                                <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-success">Details</a>
                                                <a asp-action="Edit" asp-route-id="@item.Id" class="btn btn-warning">  Edit </a>
                                                <a asp-action="Delete" asp-route-id="@item.Id" class="btn btn-danger">Delete</a>
                                            </div>
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Nom)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Adresse)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.NumTel)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Email)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Siteweb)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.SecteurAc)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Statut)
                                    </th>
                                    <th>
                                        @Html.DisplayNameFor(model => model.Logo)
                                    </th>
                                    <th>Actions</th>
                                </tr>
                            </tfoot>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div><!--/. container-fluid -->
</section>
<!-- /.content -->
<!-- AdminLTE App -->
<script src="~/js/adminlte.min.js"></script>
<!-- AdminLTE for demo purposes -->
<script src="~/js/demo.js"></script>
<!-- DataTables  & Plugins -->
<script src="~/plugins/datatables/jquery.dataTables.min.js"></script>
<script src="~/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-responsive/js/dataTables.responsive.min.js"></script>
<script src="~/plugins/datatables-responsive/js/responsive.bootstrap4.min.js"></script>
<script src="~/plugins/datatables-buttons/js/dataTables.buttons.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.bootstrap4.min.js"></script>
<script src="~/plugins/jszip/jszip.min.js"></script>
<script src="~/plugins/pdfmake/pdfmake.min.js"></script>
<script src="~/plugins/pdfmake/vfs_fonts.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.html5.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.print.min.js"></script>
<script src="~/plugins/datatables-buttons/js/buttons.colVis.min.js"></script>
<!-- Page specific script -->
<script>
    $(function () {
        $("#example1").DataTable({
            "responsive": true, "lengthChange": false, "autoWidth": false,
            "buttons": ["copy", "csv", "excel", "pdf", "print", "colvis"]
        }).buttons().container().appendTo('#example1_wrapper .col-md-6:eq(0)');
    });
</script>